<?php

namespace Idez\Caradhras\Data;

use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * @property Transaction[] $items
 * @property int $number
 * @property int $size
 * @property int $totalPages
 * @property int $totalItems
 * @property int $numberOfElements
 * @property int $maxItemsPerPage
 * @property int $totalItemsPage
 * @property bool $last
 * @property int $nextPage
 * @property int $previousPage
 * @property int $currentPage
 */
class TransactionCollection extends DataCollection
{
    use HasFactory;

    protected static function getEntity(): string
    {
        return Transaction::class;
    }

    protected static function getKey(): string
    {
        return 'items'; // TODO: Change the autogenerated stub
    }
}
